<?php 

class Productview_model extends CI_model {

public function querybuilder(){
$query = $this->db->get('BARANG', 10, 20);
return $query->result();
}


 public function filter($smax, $smin,$search,$limit, $start, $order_ascdesc){
  $this->db->select("DETAILPEMBELIAN.ID_BARANG,
    BARANG.NAMA_BARANG,
    BARANG.STOK_OPNAME, 
    (JUAL.AVERAGE)*".$smin.", 
    (JUAL.AVERAGE)*".$smax.", 
    S.NAMA_SUPPLIER, 
    S.HP, 
    BARANG.SATUAN_PEMBELIAN,
  CEILING(CEILING(JUAL.AVERAGE*".$smax.")/BARANG.ISI)
    ");
  $this->db->from ('DETAILPEMBELIAN');

 $this->db->join('(SELECT DETAILPEMBELIAN.ID_BARANG, CAST(DETAILPEMBELIAN.TANGGAL AS DATE) AS MAXDATE
    FROM DETAILPEMBELIAN)LASTBOT
    ','DETAILPEMBELIAN.ID_BARANG=LASTBOT.ID_BARANG AND
     CAST(DETAILPEMBELIAN.TANGGAL AS DATE) = LASTBOT.MAXDATE' );


  $this->db->join('BARANG', 
    'DETAILPEMBELIAN.ID_BARANG=BARANG.ID_BARANG');

  $this->db->join('PEMBELIAN',
    'PEMBELIAN.ID_PEMBELIAN = DETAILPEMBELIAN.ID_PEMBELIAN', 
    'DETAILPEMBELIAN.ID_BARANG=BARANG.ID_BARANG');
  
  $this->db->join('(SELECT * FROM SUPPLIER WHERE SUPPLIER.ID_SUPPLIER NOT IN (6)) S', 
  'PEMBELIAN.ID_SUPPLIER = S.ID_SUPPLIER');

  $this->db->join("(SELECT DETAILPENJUALAN.ID_BARANG, SUM(DETAILPENJUALAN.QTY)/90 AS AVERAGE 
    FROM DETAILPENJUALAN
    WHERE
    DATEDIFF(DAY FROM CAST(DETAILPENJUALAN.TANGGAL AS DATE) TO 
    CAST('31-Aug-2019' AS DATE)) BETWEEN 1 AND 90
    GROUP BY DETAILPENJUALAN.ID_BARANG) JUAL",
    'DETAILPEMBELIAN.ID_BARANG = JUAL.ID_BARANG');   
  
   // Untuk menambahkan query where LIKE
   // Untuk menambahkan query where OR LIKE

  $this->db->order_by('BARANG.STOK_OPNAME', $order_ascdesc);

  $this->db->order_by('S.NAMA_SUPPLIER', $order_ascdesc);
  
  $this->db->limit($limit, $start);

  // 
  
  $this->db->where("BARANG.STOK_OPNAME <= (CEILING(JUAL.AVERAGE *".$smin.")) AND( S.NAMA_SUPPLIER LIKE '".$search."%' OR BARANG.NAMA_BARANG LIKE '".$search."%')");
  
 
  return $this->db->get()->result_array();
 
  }
  

   public function count_all($smin){
    
    $query = $this->db->query(
      "SELECT DPBELI.ID_BARANG as ID, 
  CAST(DPBELI.TANGGAL AS DATE), 
  PEMBELIAN.ID_SUPPLIER as ISUP, 
  BARANG.NAMA_BARANG AS OBAT, 
  BARANG.STOK_OPNAME AS OPNAME, 
  CEILING(JUAL.AVERAGE*3) AS STOCKMIN, 
  (JUAL.AVERAGE*14) AS STOKMAX, 
  S.NAMA_SUPPLIER, s.telepon
FROM DETAILPEMBELIAN AS DPBELI

JOIN
    (SELECT DETAILPEMBELIAN.ID_BARANG, MAX(CAST(DETAILPEMBELIAN.TANGGAL AS DATE)) AS MAXDATE
    FROM DETAILPEMBELIAN
    GROUP BY DETAILPEMBELIAN.ID_BARANG)LASTBOT 
ON DPBELI.ID_BARANG = LASTBOT.ID_BARANG
AND CAST(DPBELI.TANGGAL AS DATE) = LASTBOT.MAXDATE

JOIN PEMBELIAN ON
PEMBELIAN.ID_PEMBELIAN = DPBELI.ID_PEMBELIAN

JOIN BARANG ON
DPBELI.ID_BARANG = BARANG.ID_BARANG

JOIN (SELECT DETAILPENJUALAN.ID_BARANG, SUM(DETAILPENJUALAN.QTY)/90 AS AVERAGE 
      FROM DETAILPENJUALAN
      WHERE
      DATEDIFF(DAY FROM CAST(DETAILPENJUALAN.TANGGAL AS DATE) TO 
      CAST(CURRENT_TIMESTAMP AS DATE)) BETWEEN 1 AND 90
      GROUP BY DETAILPENJUALAN.ID_BARANG) JUAL
  ON
  DPBELI.ID_BARANG = JUAL.ID_BARANG     

JOIN (SELECT * FROM SUPPLIER WHERE SUPPLIER.ID_SUPPLIER NOT IN (6)) S

ON
PEMBELIAN.ID_SUPPLIER = S.ID_SUPPLIER

WHERE BARANG.STOK_OPNAME <= (CEILING(JUAL.AVERAGE *".$smin."))


 ;");
    return $query->num_rows();
  }

   function count_filter($smin,$search){

   $sql = 
      "SELECT DPBELI.ID_BARANG as ID
      FROM DETAILPEMBELIAN AS DPBELI

    JOIN
    (SELECT DETAILPEMBELIAN.ID_BARANG, MAX(CAST(DETAILPEMBELIAN.TANGGAL AS DATE)) AS MAXDATE
    FROM DETAILPEMBELIAN
    GROUP BY DETAILPEMBELIAN.ID_BARANG)LASTBOT 
ON DPBELI.ID_BARANG = LASTBOT.ID_BARANG
AND CAST(DPBELI.TANGGAL AS DATE) = LASTBOT.MAXDATE

JOIN PEMBELIAN ON
PEMBELIAN.ID_PEMBELIAN = DPBELI.ID_PEMBELIAN

JOIN BARANG ON BARANG.ID_BARANG = DPBELI.ID_BARANG

JOIN (SELECT DETAILPENJUALAN.ID_BARANG, SUM(DETAILPENJUALAN.QTY)/90 AS AVERAGE 
      FROM DETAILPENJUALAN
      WHERE
      DATEDIFF(DAY FROM CAST(DETAILPENJUALAN.TANGGAL AS DATE) TO 
      CAST(CURRENT_TIMESTAMP AS DATE)) BETWEEN 1 AND 90
      GROUP BY DETAILPENJUALAN.ID_BARANG) JUAL
  ON
  DPBELI.ID_BARANG = JUAL.ID_BARANG     

JOIN (SELECT * FROM SUPPLIER WHERE SUPPLIER.ID_SUPPLIER NOT IN (6)) S
ON
PEMBELIAN.ID_SUPPLIER = S.ID_SUPPLIER
WHERE BARANG.STOK_OPNAME <= (CEILING(JUAL.AVERAGE *".$smin.")) AND( S.NAMA_SUPPLIER LIKE '".$search."%' OR BARANG.NAMA_BARANG LIKE '".$search."%')";
$stmt = $this->db->query($sql);
  return $stmt->num_rows(); 
  }
}



?>